### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by theshortcut** [pshomov/webdesktop2#1]
Currently on the main monitor gets the set desktop. It'd be nice if at the very least it was duplicated on the other monitors. Even better would be allowing for a different url per monitor.

**Comment by pshomov** [comment]
I will look into this over Christmas.

**Comment by pshomov** [comment]
This is working now, needs some testing. Will render the same page on all screens. Need to add a configuration for the secondary monitors url may be?
